/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { FormConfig } from './types';

export const FORM_CONFIGS: FormConfig[] = [
  {
    id: 'CLINIC_TO_CRYOFUTURE_BULK',
    title: 'Clinic to CryoFuture',
    description: 'Local Verification Form',
    fields: [
      'referenceNumber',
      'clientName',
      'clientDob',
      'coClientName',
      'coClientDob',
      'specimenTypes',
      'otherSpecimenType',
      'sendingClinic',
      'numberOfCanes',
      'numberOfStrawsVials',
      'infectiousStatus',
      'sendingTemp',
      'loadingTime',
      'sendingClinicStaffName',
      'sendingClinicDate',
      'shipperInspected',
      'liquidNitrogenRefilled',
      'cryoFacilityTemp',
      'unloadingTime',
      'shipperNumber',
      'cryofutureStaffName',
      'cryofutureDate',
    ],
  },
  {
    id: 'CLINIC_TO_CLINIC_TRANSPORT',
    title: 'Clinic to Clinic Transport',
    description: 'Local Courier Verification Form',
    fields: [
      'referenceNumber',
      'clientName',
      'clientDob',
      'coClientName',
      'coClientDob',
      'specimenTypes',
      'otherSpecimenType',
      'sendingClinic',
      'numberOfCanes',
      'numberOfStrawsVials',
      'infectiousStatus',
      'sendingTemp',
      'loadingTime',
      'sendingClinicStaffName',
      'sendingClinicDate',
      'receivingClinic',
      'receivingTemp',
      'unloadingTimeReceiving',
      'receivingClinicStaffName',
      'receivingClinicDate',
      'idVerified',
      'receiptAcknowledged',
      'shipperNumber',
      'cryofutureStaffName',
      'cryofutureDate',
    ],
  },
  {
    id: 'CRYOFUTURE_TO_CLINIC_TRANSPORT',
    title: 'CryoFuture to Clinic for Transport',
    description: 'Local Courier Verification Form',
    fields: [
      'referenceNumber',
      'clientName',
      'clientDob',
      'coClientName',
      'coClientDob',
      'specimenTypes',
      'otherSpecimenType',
      'numberOfCanes',
      'numberOfStrawsVials',
      'infectiousStatus',
      'sendingTemp',
      'loadingTime',
      'shipperNumber',
      'cryofutureStaffName',
      'cryofutureDate',
      'receivingClinic',
      'receivingTemp',
      'unloadingTimeReceiving',
      'receivingClinicStaffName',
      'receivingClinicDate',
    ],
  },
];
